---

- name: Setting up a Jenkins instance
  hosts: default

  gather_facts: yes

  become: yes

  tasks:
    - name: Install dependencies
      apt:
        pkg:
          - openjdk-11-jdk
          - python3
          - python3-pip

    - name: Get the Jenkins key from the official servers
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Adding the Jenkins deb repo to the source list
      apt_repository:
        repo: deb http://pkg.jenkins-ci.org/debian-stable binary/
        state: present
        filename: "jenkins"
        update_cache: yes

    - name: Manually update_cache
      apt:
        update_cache: yes

    - name: Installing Jenkins and start
      apt:
        name: jenkins
        state: present
        force: yes

    - name: Add jenkins user to the docker group
      user:
        name: jenkins
        groups: 'docker'
        append: yes

    - name: Restart docker.service
      service:
        name: docker
        state: restarted
